name: actionlint-action self-test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  self-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Test happy path
        uses: ./
        with:
          paths: test/fixtures/valid/.github/workflows/valid.yml

      - name: Test glob paths input
        uses: ./
        with:
          paths: test/fixtures/valid/.github/workflows/*.yml

      - name: Test directory paths input
        uses: ./
        with:
          paths: test/fixtures/valid/.github/workflows

      - name: Test invalid fixture
        id: invalid-fixture
        uses: ./
        continue-on-error: true
        with:
          paths: test/fixtures/invalid/.github/workflows/invalid.yml

      - name: Assert invalid fixture failed
        if: steps.invalid-fixture.outcome != 'failure'
        run: exit 1

      - name: Test config-file
        uses: ./
        with:
          config-file: test/fixtures/config/.github/actionlint.yaml
          paths: test/fixtures/config/.github/workflows/ignored.yml

      - name: Test ignore input
        uses: ./
        with:
          ignore: 'unexpected key "foo" for "workflow" section.*'
          paths: test/fixtures/config/.github/workflows/ignored.yml

      - name: Test tool disable
        uses: ./
        with:
          shellcheck: ""
          pyflakes: ""
          paths: test/fixtures/valid/.github/workflows/valid.yml

      - name: Test no-color/oneline/format inputs
        uses: ./
        with:
          no-color: false
          oneline: true
          format: '{{range $err := .}}{{println $err.Message}}{{end}}'
          paths: test/fixtures/valid/.github/workflows/valid.yml
